# Generated by Django 5.2.4 on 2025-08-04 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_especializacao_dadosmedico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndisponibilidadeMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(limit_choices_to={'cargo': 'M'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indisponibilidade do Médico',
                'verbose_name_plural': 'Indisponibilidades dos Médicos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(verbose_name='Data da Consulta')),
                ('hora_consulta', models.TimeField(verbose_name='Hora da Consulta')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo da Consulta')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tipo_convenio', models.CharField(choices=[('sus', 'SUS'), ('particular', 'Particular'), ('plano', 'Plano de Saúde')], default='sus', max_length=20)),
                ('plano_saude', models.CharField(blank=True, choices=[('amil', 'Amil'), ('unimed', 'Unimed'), ('bradesco', 'Bradesco Saúde'), ('sulamerica', 'SulAmérica'), ('outros', 'Outros')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Paciente Faltou')], default='agendada', max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Consulta')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_criadas', to=settings.AUTH_USER_MODEL)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.especializacao')),
                ('medico', models.ForeignKey(limit_choices_to={'cargo': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'cargo': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['data_consulta', 'hora_consulta'],
                'unique_together': {('medico', 'data_consulta', 'hora_consulta')},
            },
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(limit_choices_to={'cargo': 'M'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
