# Generated by Django 5.2.4 on 2025-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('R', 'Recepcionista'), ('M', 'Médico'), ('G', 'Gerente'), ('P', 'Paciente')], default='P', max_length=1),
        ),
    ]
