# Generated by Django 5.2.4 on 2025-08-04 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_users_cpf_users_telefone_alter_users_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especializacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Especialização')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo_cbo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código CBO')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especialização',
                'verbose_name_plural': 'Especializações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DadosMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=15, unique=True, verbose_name='CRM')),
                ('uf_crm', models.CharField(max_length=2, verbose_name='UF do CRM')),
                ('valor_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Consulta')),
                ('tempo_consulta', models.PositiveIntegerField(default=30, verbose_name='Tempo de Consulta (minutos)')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('formacao', models.TextField(blank=True, null=True, verbose_name='Formação Acadêmica')),
                ('experiencia', models.TextField(blank=True, null=True, verbose_name='Experiência Profissional')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Fim')),
                ('dias_semana', models.CharField(blank=True, help_text='Ex: 1,2,3,4,5 (Segunda a Sexta)', max_length=20, null=True, verbose_name='Dias da Semana')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'cargo': 'M'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('especializacoes', models.ManyToManyField(to='usuarios.especializacao', verbose_name='Especializações')),
            ],
            options={
                'verbose_name': 'Dados do Médico',
                'verbose_name_plural': 'Dados dos Médicos',
            },
        ),
    ]
